# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tarefas_pb2 as tarefas__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tarefas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GerenciadorTarefasStub(object):
    """--- O serviço ---
    Cada rpc vira um método no stub do cliente e um método na classe base
    do servidor.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarTarefa = channel.unary_unary(
                '/tarefas.GerenciadorTarefas/CriarTarefa',
                request_serializer=tarefas__pb2.CriarTarefaRequest.SerializeToString,
                response_deserializer=tarefas__pb2.CriarTarefaResponse.FromString,
                _registered_method=True)
        self.ListarTarefas = channel.unary_unary(
                '/tarefas.GerenciadorTarefas/ListarTarefas',
                request_serializer=tarefas__pb2.ListarTarefasRequest.SerializeToString,
                response_deserializer=tarefas__pb2.ListarTarefasResponse.FromString,
                _registered_method=True)
        self.AtualizarTarefa = channel.unary_unary(
                '/tarefas.GerenciadorTarefas/AtualizarTarefa',
                request_serializer=tarefas__pb2.AtualizarTarefaRequest.SerializeToString,
                response_deserializer=tarefas__pb2.AtualizarTarefaResponse.FromString,
                _registered_method=True)
        self.DeletarTarefa = channel.unary_unary(
                '/tarefas.GerenciadorTarefas/DeletarTarefa',
                request_serializer=tarefas__pb2.DeletarTarefaRequest.SerializeToString,
                response_deserializer=tarefas__pb2.DeletarTarefaResponse.FromString,
                _registered_method=True)
        self.AcompanharTarefas = channel.unary_stream(
                '/tarefas.GerenciadorTarefas/AcompanharTarefas',
                request_serializer=tarefas__pb2.ListarTarefasRequest.SerializeToString,
                response_deserializer=tarefas__pb2.Tarefa.FromString,
                _registered_method=True)


class GerenciadorTarefasServicer(object):
    """--- O serviço ---
    Cada rpc vira um método no stub do cliente e um método na classe base
    do servidor.
    """

    def CriarTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarTarefas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcompanharTarefas(self, request, context):
        """Versão em server streaming da listagem. Mesma informação, entregue
        uma tarefa por vez em vez de tudo de uma vez. Bom material para a
        apresentação: mostra algo que REST tradicional não faz naturalmente.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GerenciadorTarefasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarTarefa,
                    request_deserializer=tarefas__pb2.CriarTarefaRequest.FromString,
                    response_serializer=tarefas__pb2.CriarTarefaResponse.SerializeToString,
            ),
            'ListarTarefas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarTarefas,
                    request_deserializer=tarefas__pb2.ListarTarefasRequest.FromString,
                    response_serializer=tarefas__pb2.ListarTarefasResponse.SerializeToString,
            ),
            'AtualizarTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarTarefa,
                    request_deserializer=tarefas__pb2.AtualizarTarefaRequest.FromString,
                    response_serializer=tarefas__pb2.AtualizarTarefaResponse.SerializeToString,
            ),
            'DeletarTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarTarefa,
                    request_deserializer=tarefas__pb2.DeletarTarefaRequest.FromString,
                    response_serializer=tarefas__pb2.DeletarTarefaResponse.SerializeToString,
            ),
            'AcompanharTarefas': grpc.unary_stream_rpc_method_handler(
                    servicer.AcompanharTarefas,
                    request_deserializer=tarefas__pb2.ListarTarefasRequest.FromString,
                    response_serializer=tarefas__pb2.Tarefa.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarefas.GerenciadorTarefas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarefas.GerenciadorTarefas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GerenciadorTarefas(object):
    """--- O serviço ---
    Cada rpc vira um método no stub do cliente e um método na classe base
    do servidor.
    """

    @staticmethod
    def CriarTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorTarefas/CriarTarefa',
            tarefas__pb2.CriarTarefaRequest.SerializeToString,
            tarefas__pb2.CriarTarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarTarefas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorTarefas/ListarTarefas',
            tarefas__pb2.ListarTarefasRequest.SerializeToString,
            tarefas__pb2.ListarTarefasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorTarefas/AtualizarTarefa',
            tarefas__pb2.AtualizarTarefaRequest.SerializeToString,
            tarefas__pb2.AtualizarTarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorTarefas/DeletarTarefa',
            tarefas__pb2.DeletarTarefaRequest.SerializeToString,
            tarefas__pb2.DeletarTarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcompanharTarefas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tarefas.GerenciadorTarefas/AcompanharTarefas',
            tarefas__pb2.ListarTarefasRequest.SerializeToString,
            tarefas__pb2.Tarefa.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
